export const enum ACTION_TYPES {
  // Fetch products
  FETCH_PRODUCTS_PENDING = 'FETCH_PRODUCTS_PENDING',
  FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS',
  FETCH_PRODUCTS_ERROR = 'FETCH_PRODUCTS_ERROR',

  // Fetch product details
  FETCH_PRODUCT_DETAILS_PENDING = 'FETCH_PRODUCT_DETAILS_PENDING',
  FETCH_PRODUCT_DETAILS_SUCCESS = 'FETCH_PRODUCT_DETAILS_SUCCESS',
  FETCH_PRODUCT_DETAILS_ERROR = 'FETCH_PRODUCT_DETAILS_ERROR',

  // Fetch categories
  FETCH_CATEGORIES_PENDING = 'FETCH_CATEGORIES_PENDING',
  FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS',
  FETCH_CATEGORIES_FAILURE = 'FETCH_CATEGORIES_FAILURE',

  // Add to cart
  ADD_TO_CART_PENDING = 'ADD_TO_CART_PENDING',
  ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS',
  ADD_TO_CART_FAILED = 'ADD_TO_CART_FAILED',

  // Fetch carts
  FETCH_CART_PENDING = 'FETCH_CART_PENDING',
  FETCH_CART_SUCCESS = 'FETCH_CART_SUCCESS',
  FETCH_CART_FAILED = 'FETCH_CART_FAILED',

  // Quantity control
  INCREASE_QUANTITY_IN_CART = 'INCREASE_QUANTITY_IN_CART',
  DECREASE_QUANTITY_IN_CART = 'DECREASE_QUANTITY_IN_CART',
  CHANGE_QUANTITY_IN_CART = 'CHANGE_QUANTITY_IN_CART',

  // Remove from cart
  REMOVE_FROM_CART_PENDING = 'REMOVE_FROM_CART_PENDING',
  REMOVE_FROM_CART_SUCCESS = 'REMOVE_FROM_CART_SUCCES',
  REMOVE_FROM_CART_FAILED = 'REMOVE_FROM_CART_FAILED',

  // List type change
  SET_LIST_TYPE = 'SET_LIST_TYPE'
}
